<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./src/public/css/button-drop.css">
    <title>Document</title>
</head>

<body>
    <?php var_dump($matrix); ?>


    <div class="m-dropdown">
        <div class="e-button open">
            Click Me
            <div class="e-burger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <ul class="e-list">
            <li><a href="#">Item 1</a></li>
            <li><a href="#">Item 2</a></li>
            <li><a href="#">Item 3</a></li>
            <li><a href="#">Item 4</a></li>
            <li><a href="#">Item 5</a></li>
        </ul>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="./src/public/js/button-drop.js"></script>
</body>

</html>