<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/dragdrop.css">
    <title>Spreadsheet</title>
</head>

<body>
    <h2>Gestion Documental</h2>

    <form action="/getinfo" method="POST" enctype="multipart/form-data">
        <div class="file-drop-area">
            <span class="fake-btn">Elige Archivo</span>
            <span class="file-msg">o arrastra y suelta los archivos aqui</span>
            <input class="file-input" name="document" type="file" required>
        </div>
        <button class="fake-btn">Enviar</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="./js/dragdrop.js"></script>
</body>

</html>